services:
  comfyui:
    env_file:
      - ./.env
      - ./comfyui/override.env
    container_name: ${HARBOR_CONTAINER_PREFIX}.comfyui
    image: yanwk/comfyui-boot:${HARBOR_COMFYUI_VERSION}
    environment:
      - CLI_ARGS=
    ports:
      - ${HARBOR_COMFYUI_HOST_PORT}:8188
    volumes:
      - ${HARBOR_COMFYUI_WORKSPACE}/storage:/root
      - ${HARBOR_COMFYUI_WORKSPACE}/models:/root/ComfyUI/models
      - ${HARBOR_HF_CACHE}/hub:/root/.cache/huggingface/hub
      - ${HARBOR_COMFYUI_WORKSPACE}/user:/root/ComfyUI/user
      - ${HARBOR_COMFYUI_WORKSPACE}/input:/root/ComfyUI/input
      - ${HARBOR_COMFYUI_WORKSPACE}/output:/root/ComfyUI/output
    networks:
      - harbor-network
